import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import MainLayout from "@/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
